### ISSUE TITLE
.env sample

### ISSUE THREAD

**Issue by smallcar88** [mya-ake/nuxt-on-lambda#6]
Hello, I have been following your code for my first Lambda Nuxt program. I can see you have included a dotenv package to load the .env for secrets and config settings. Would you mind sharing a sample of .env? Thank you!

**Comment by mya-ake** [comment]
@smallcar88 
I forgot to add it.
Thank you for creating the issue.

I have added [.env.sample](https://github.com/mya-ake/nuxt-on-lambda/blob/master/.env.sample).
