### ISSUE TITLE
ERROR  spawn yarn ENOENT (windows os)

### ISSUE THREAD

**Issue by tomasSlouka** [mya-ake/nuxt-on-lambda#7]
Hi,

you are doing a great job. Thank you.

I encounter an issue when run `npm run deploy` I get an error

> ERROR  spawn yarn ENOENT                                                                                                                          16:39:24
> 
>   at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
>   at onErrorNT (internal/child_process.js:431:16)
>   at processTicksAndRejections (internal/process/task_queues.js:81:17)
>   at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
>   at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
>   at internal/main/run_main_module.js:21:11
> 
> error Command failed with exit code 1.

I found that this error is caused by windows os and that it can be fixed by using 
https://www.npmjs.com/package/cross-spawn. Will you mind to make a fix?

Thanks

**Comment by mya-ake** [comment]
@tomasSlouka 

Thank you for reporting!

I have fixed. Please let me know if there is a problem again.
At that time, it is okay to PR.

Thanks.
